In [1]:
using Printf
using Statistics

### Initiation

In [4]:
s = 0
s = "Hello World"

println(s)

Hello World

### Asserting data type

In [7]:
function changenum()
    x::Int8 = 10
    x = "Dog"
end

changenum (generic function with 1 method)

In [8]:
changenum()

MethodError: MethodError: Cannot `convert` an object of type String to an object of type Int8
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Ptr) where T<:Integer at pointer.jl:23
  ...

In [10]:
can_drive = true

if can_drive
    println("Can drive")
end

Can drive


In [14]:
c2 = Char(65)
println(c2)

A


In [16]:
i1 = UInt8(trunc(3.14))
println(i1)

3


In [17]:
s1 = "Random string"

println(length(s1))

13


In [21]:
println(s1[1])
println(s1[end])
println(string(s1[1:4],"Bonus"))
println(s1[1:4]*"Bonus")

R
g
RandBonus
RandBonus


In [22]:
i1, i2, i3 = 1, 2, 3

(1, 2, 3)

In [25]:
println("$i1 + $i2 = $(i1+i2)")

1 + 2 = 3


In [41]:
# Comments

## Conditions and loops

In [29]:
i1 > i2

false

In [30]:
println(findfirst(isequal('i'), "Testi"))

5


In [31]:
println(occursin("test", "tetestte"))

true


In [34]:
age = 21
if age < 18 && age > 14
    println("High School")
elseif age > 18
    println("Uni")
end

Uni


In [35]:
@printf("Answer = %s", !true ? "true" : "false")

Answer = false

In [36]:
println(true || false) # or

true


In [38]:
i = 1
while i<=20
    if i % 2 == 0
        println(i)
    end
    global i += 1
end
    

2
4
6
8
10
12
14
16
18
20


In [39]:
for i = 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [40]:
for i in [2, 4, 6, 8]
    println(i)
end

2
4
6
8


## Arrays

In [42]:
a1 = zeros(Int32, 2, 2)
println(a1)

Int32[0 0; 0 0]


In [43]:
println(Array{Int32}(undef, 5))

Int32[224200800, 0, 390136000, 0, 390136064]


In [46]:
f(a) = (a<=2) ? true : false
a2 = [0, 1, 2, 3]
println(findall(f, a2))

[1, 2, 3]


In [47]:
splice!(a2, 2:1, [7, 8])
println(a2)

[0, 7, 8, 1, 2, 3]

In [48]:
println(maximum(a2))
println(minimum(a2))

8
0


In [50]:
fnc = [cos, sin, tan]
for func in fnc
    println(func(0))
end

1.0
0.0
0.0


In [52]:
a3 = [1 2 3; 4 5 6]
println(a3)

[1 2 3; 4 5 6]


In [53]:
println(a3[:,1])

[1, 4]


In [56]:
a4 = [n^2 for n in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [57]:
println(a4)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [58]:
push!(a4, 121)

11-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100
 121

In [59]:
a5 = rand(0:9, 5, 5)

5×5 Array{Int64,2}:
 7  1  1  7  9
 1  4  8  2  5
 2  9  8  5  0
 4  5  6  8  6
 6  3  0  0  7

In [60]:
println(a5)

[7 1 1 7 9; 1 4 8 2 5; 2 9 8 5 0; 4 5 6 8 6; 6 3 0 0 7]


## Tuples

Most functions will work on tuple, only tuples are unmutable

In [61]:
t1 = (1, 2, 3, 4)

(1, 2, 3, 4)

In [63]:
println(t1)
println(t1[1])

(1, 2, 3, 4)
1


In [66]:
t2 = ((1, 2), (3, 4))
println(t2[1][2])

2


In [69]:
t3 = (john = ("John", 2), suzanne = ("Suzanne", 3))

(john = ("John", 2), suzanne = ("Suzanne", 3))

In [70]:
println(t3.john)

("John", 2)


## Dictionaries

In [71]:
d1 = Dict("pi"=>3.14, "e" => 2.71)

Dict{String,Float64} with 2 entries:
  "e"  => 2.71
  "pi" => 3.14

In [72]:
d1["pi"]

3.14

In [73]:
d1["golden"] = 1.618

1.618

In [74]:
delete!(d1, "pi")

Dict{String,Float64} with 2 entries:
  "golden" => 1.618
  "e"      => 2.71

In [77]:
haskey(d1, "pi")

false

In [79]:
for (key, val) in d1
    println(key, ": ", val)
end

golden: 1.618
e: 2.71


## Set

In [80]:
set1 = Set(["Jim", "Tom", "Paul"])

Set{String} with 3 elements:
  "Tom"
  "Jim"
  "Paul"

In [82]:
push!(set1, "Jim")

Set{String} with 3 elements:
  "Tom"
  "Jim"
  "Paul"

In [83]:
set2 = Set(["Jim", "John"])

Set{String} with 2 elements:
  "Jim"
  "John"

In [84]:
union(set1, set2)

Set{String} with 4 elements:
  "Tom"
  "Jim"
  "John"
  "Paul"

In [85]:
intersect(set1, set2)

Set{String} with 1 element:
  "Jim"

In [86]:
setdiff(set1, set2)

Set{String} with 2 elements:
  "Tom"
  "Paul"

## Functions

In [87]:
getsum(x, y) = x+y

getsum (generic function with 1 method)

In [88]:
x, y = 1, 2
println(getsum(x, y))

3


In [89]:
function canvote(age = 16)
    if age >= 16
        println("Can vote")
    else
        println("Can't")
    end
end

canvote (generic function with 2 methods)

In [90]:
canvote(32)

Can vote


In [98]:
function changev1()
    global v1 = 5
end

changev1 (generic function with 2 methods)

In [92]:
v1 = 1

1

In [99]:
changev1()

5

In [100]:
v1

5

In [103]:
function getsum(args...)
    sum = 0
    for val in args
        sum += val
    end
    return sum
end

getsum (generic function with 2 methods)

In [104]:
getsum(1,2,3)

6

## Anonymous functions

In [105]:
ano1 = map(x -> x^2, [1, 2, 3])

3-element Array{Int64,1}:
 1
 4
 9

In [107]:
ano1

3-element Array{Int64,1}:
 1
 4
 9

In [109]:
map((x, y) -> x+y, [1, 2], [3,4])

2-element Array{Int64,1}:
 4
 6

In [110]:
reduce(+, 1:100)

5050

In [111]:
sentence = "This is a string"
sarray = split(sentence)

4-element Array{SubString{String},1}:
 "This"
 "is"
 "a"
 "string"

In [114]:
reduce((x, y) -> length(x) > length(y) ? x : y, sarray)

"string"

## Enums

In [115]:
@enum Color begin
    red = 1
    blue = 2
    green =3
end

favcolor = green::Color

green::Color = 3

In [116]:
println(favcolor)

green


## Symbols

In [117]:
:John

:John

In [118]:
println(:John)

John


Often used as keys in dictionary

## Structures

In [119]:
struct Customer
    name::String
    balance::Float32
    id::Int
end

In [120]:
john = Customer("John Zhu", 12.88, 1)

Customer("John Zhu", 12.88f0, 1)

In [121]:
john.name

"John Zhu"

In [122]:
john.name = "John"

ErrorException: setfield! immutable struct of type Customer cannot be changed

In [123]:
mutable struct Customer_mut
    name::String
    balance::Float32
    id::Int
end

In [124]:
john = Customer_mut("John Zhu", 12.88, 1)

Customer_mut("John Zhu", 12.88f0, 1)

In [125]:
john.name

"John Zhu"

In [126]:
john.name = "Johnny"

"Johnny"

In [127]:
john

Customer_mut("Johnny", 12.88f0, 1)

## Abstract Types

In [128]:
abstract type Animal end

In [129]:
struct Dog <: Animal
    name::String
    bark::String
end

In [130]:
struct Cat <: Animal
    name::String
    meow::String
end

In [131]:
bowser = Dog("Bowser", "Ruff")
muffin = Cat("Muffin", "Meow")

Cat("Muffin", "Meow")

In [132]:
function makesound(animal::Dog)
    println(animal.name, animal.bark)
end


makesound (generic function with 1 method)

In [133]:
function makesound(animal::Cat)
    println(animal.name, animal.meow)
end


makesound (generic function with 2 methods)

In [134]:
makesound(bowser)

BowserRuff


In [135]:
makesound(muffin)

MuffinMeow


## Error handling

In [149]:
num1 = 8
num2 = 0
try
    val = num1/num2
    if val == Inf
        error("Can't divide by zero")
    else
        println(val)
    end
catch e
    println(e)
end
    

ErrorException("Can't divide by zero")


In [140]:
3/0

Inf

## Macros

In [150]:
macro domore(n, exp)
    quote
        for i =1:$(esc(n))
            $(esc(exp))
        end
    end
end

@domore (macro with 1 method)

In [152]:
@domore(3, println(3+4))

7
7
7


In [155]:
@assert 3+4 == 7